/*
Copyright 2020 The Flux authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha3

import (
	v1alpha3 "github.com/fluxcd/flagger/pkg/apis/istio/v1alpha3"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// EnvoyFilterLister helps list EnvoyFilters.
// All objects returned here must be treated as read-only.
type EnvoyFilterLister interface {
	// List lists all EnvoyFilters in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha3.EnvoyFilter, err error)
	// EnvoyFilters returns an object that can list and get EnvoyFilters.
	EnvoyFilters(namespace string) EnvoyFilterNamespaceLister
	EnvoyFilterListerExpansion
}

// envoyFilterLister implements the EnvoyFilterLister interface.
type envoyFilterLister struct {
	listers.ResourceIndexer[*v1alpha3.EnvoyFilter]
}

// NewEnvoyFilterLister returns a new EnvoyFilterLister.
func NewEnvoyFilterLister(indexer cache.Indexer) EnvoyFilterLister {
	return &envoyFilterLister{listers.New[*v1alpha3.EnvoyFilter](indexer, v1alpha3.Resource("envoyfilter"))}
}

// EnvoyFilters returns an object that can list and get EnvoyFilters.
func (s *envoyFilterLister) EnvoyFilters(namespace string) EnvoyFilterNamespaceLister {
	return envoyFilterNamespaceLister{listers.NewNamespaced[*v1alpha3.EnvoyFilter](s.ResourceIndexer, namespace)}
}

// EnvoyFilterNamespaceLister helps list and get EnvoyFilters.
// All objects returned here must be treated as read-only.
type EnvoyFilterNamespaceLister interface {
	// List lists all EnvoyFilters in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha3.EnvoyFilter, err error)
	// Get retrieves the EnvoyFilter from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha3.EnvoyFilter, error)
	EnvoyFilterNamespaceListerExpansion
}

// envoyFilterNamespaceLister implements the EnvoyFilterNamespaceLister
// interface.
type envoyFilterNamespaceLister struct {
	listers.ResourceIndexer[*v1alpha3.EnvoyFilter]
}
